### ISSUE TITLE
Vault Script - server 2016 - v12 vault

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/CYBRHardeningCheck#11]
When running the script on a vault server, although the step 'Advanced Audit Policy Configuration' states as being 'good' in the report the output of the powershell script shows an error when checking one of the audit settings

![image](https://user-images.githubusercontent.com/12948477/102815216-f00d0180-43c3-11eb-8199-decca18c130a.png)

![image](https://user-images.githubusercontent.com/12948477/102815298-0b780c80-43c4-11eb-8772-04d8f9e3e795.png)

**Comment by AssafMiron** [comment]
Actually I found the same issue on one of my tests and fixed it today
Once I finish testing it I will commit the change
