### ISSUE TITLE
Vault script - Advanced audit policy configuration step

### ISSUE THREAD

**Issue by alanmilinovic** [cyberark/CYBRHardeningCheck#18]
When executing script on Vault server received error 0x00000057 in step advanced audit policy configuration.

![image](https://user-images.githubusercontent.com/1752983/102898931-8431a400-446a-11eb-8019-2167d9c3b315.png)

Tried on Server 2016 - Vault v 11.7

**Comment by AssafMiron** [comment]
Might be the same as #11
