### ISSUE TITLE
PSM - Screen saver error

### ISSUE THREAD

**Issue by amilino** [cyberark/CYBRHardeningCheck#19]
When checking screensaver settings error received:
![image](https://user-images.githubusercontent.com/1752983/102983046-c828b580-450b-11eb-809d-7f9fd354669b.png)

Tested on Server 2019, PSM 11.7.

**Comment by AssafMiron** [comment]
Hey @amilino ,
Could you take the changes I did in the above related commit and check if it solves your problem?
Thanks

**Comment by amilino** [comment]
It looks like problem is solved, but another one came as well.

![image](https://user-images.githubusercontent.com/1752983/103531339-6829fb80-4e89-11eb-93b5-a7b6db40eec8.png)

**Comment by AssafMiron** [comment]
Thanks Alan
I fixed the issue, I think I pushed it to the wrong branch though...
If you want to test it locally go to line 599 in the PSM hardening steps
replace this line:
  DisableScreenSaver -refOutput ([ref]$tmpStatus)
With these lines:
If((DisableScreenSaver -refOutput ([ref]$myRef)) -ne "Good")
            {
                $tmpStatus += $myRef.Value
            }

**Comment by amilino** [comment]
Glad to hear you found it. Tested, it looks fine now.
