### ISSUE TITLE
Vault check for Master/Operator keys permissions

### ISSUE THREAD

**Issue by AssafMiron** [cyberark/CYBRHardeningCheck#37]
I would like to have a check that the Master / Operator keys that might be stored on the Vault have the appropriate folder permissions

## Describe the solution you would like

Only local administrator and System should have permissions over that folder

**Comment by AssafMiron** [comment]
@itsmegb is this what you had in mind?

**Comment by NathTheDude** [comment]
@itsmegb , it should probably check (if your update does not already) check if the 'recprv.key' file exists on the file system - as we know this is bad.

**Comment by AssafMiron** [comment]
Good point @NathTheDude , I can add this check as well

**Comment by NathTheDude** [comment]
> Good point @NathTheDude , I can add this check as well

I tried to do this as part of a script before but I could not do this check without a massive hang in my script which could affect vault performance. I can not remember the commands I used so perhaps there is a better way.
