### ISSUE TITLE
Issue with running 'main.ps1', unable to determine unblocked files

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/CYBRHardeningCheck#38]
## Summary
When running the 'main.ps1' the following is seen even though all files have been unblocked:
---------
Some files are marked as blocked

To solve this you can run the following command: Get-ChildItem -Path C:\Users\AutoLoginSrvAdmin\desktop\CYBRHardeningCheck-main\CYBRHardeningCheck-main\CYBRHardeningCheck -Recurse | Unblock-File

Script ended
---------

## Steps to Reproduce
Steps to reproduce the behaviour:
1. Make sure that all files are blocked by running something similar to this: 'Get-ChildItem * -Recurse | Unblock-File
2. Run the 'main.ps1' script

## Expected Results
Script should run and not exit with a comment that files are blocked, when they are not

## Actual Results (including error logs, if applicable)
The following is seen when running the 'main.ps1' script

---------
Some files are marked as blocked

To solve this you can run the following command: Get-ChildItem -Path C:\Users\Nathan\desktop\CYBRHardeningCheck-main\CYBRHardeningCheck-main\CYBRHardeningCheck -Recurse | Unblock-File

Script ended
---------

Looking at the 'Main.ps1' script, the following code is ran for this check:

-------
# Check if relevant files are blocked
If($null -eq $(Get-ChildItem -Path $ScriptLocation -Include ('*.ps1','*.psm1','*.dll') -Recurse | Get-Item -Stream “Zone.Identifier” -ErrorAction SilentlyContinue))
{
	Write-LogMessage -Type Error -Msg "Some files are marked as blocked"
	$command = "Get-ChildItem -Path $ScriptLocation -Recurse | Unblock-File"
	Write-LogMessage -Type Info -Msg "To solve this you can run the following command: $command"
	Write-LogMessage -Type Info -Msg "Script ended"
	return
}
-------

When running the following on files that are not blocked (as an example), the value for 'Stream' is '$Data' and not $NULL which is expected from the script (or so I believe)

-------
Get-ChildItem | Get-Item -Stream *
---
PSPath        : Microsoft.PowerShell.Core\FileSystem::C:\Users\AutoLoginSrvAdmin\desktop\CYBRHardeningCheck-main\CYBRHardeningCheck-main\CYBRHardeningCheck\Main.ps1::$DATA
PSParentPath  : Microsoft.PowerShell.Core\FileSystem::C:\Users\AutoLoginSrvAdmin\desktop\CYBRHardeningCheck-main\CYBRHardeningCheck-main\CYBRHardeningCheck
PSChildName   : Main.ps1::$DATA
PSProvider    : Microsoft.PowerShell.Core\FileSystem
PSIsContainer : False
FileName      : C:\Users\AutoLoginSrvAdmin\desktop\CYBRHardeningCheck-main\CYBRHardeningCheck-main\CYBRHardeningCheck\Main.ps1
Stream        : :$DATA
Length        : 15853
---
------

## Reproducible
  [Y] Always 

## Version/Tag number
Not relevant for this bug

## Environment setup
Don't believe this is relevant but I have test two different branches on two VM's (PAS v12.0) and got the same results.

## Additional Information
Changing the code from '-eq' to '-ne' resolves the issue however this probably does not detect if a file is blocked though.

**Comment by AssafMiron** [comment]
Thanks @NathTheDude 
I noticed it too and changed "eq" to "ne"
From what I checked it did solve the issue and still detected the blocked files
This will be part of #35 

Thanks,
Assaf
