### ISSUE TITLE
PVWA - Hardening step 'PVWA not installed on System Drive'

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/CYBRHardeningCheck#39]
This step checks if the IIS website for PVWA has been installed on to the system drive, if it is then a 'warning' is given for this check.

Some points that are worth clarifying/updating 
- Would be good to add this recommendation to the public CyberArk documentation, if this is not recommended in this documentation then Ideally it should not be a 'warning' if this was never suggested/recommended.
- When the above is added to the external documentation, a link could be added for this and also a link to Microsoft documentation/article mentioning that this is not recommended

**Comment by AssafMiron** [comment]
Thanks @NathTheDude 
I'll check internally with R&D if they plan on adding this recommendation to the docs
In the meanwhile I will add a link to Microsoft recommendation

Thanks,
Assaf
