### ISSUE TITLE
PVWA Hardening check - 'Disable services'

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/CYBRHardeningCheck#40]
The CyberArk PVWA hardening script only disables the following services (as of v12.0):
- Routing and Remote Access,
- Smart Card
- Smart Card Removal Policy
- SNMP Trap
- Special Administration Console Helper
- Windows Error Reporting Service

As part of the 'Disable Services' check within the PVWA Hardening script, the service ''WinHTTP Web Proxy Auto-Discovery Service' is check to see if the startup is set to 'disabled'.
As part of the 'Disable Services' check within the PVWA Hardening script, the service ''WinHTTP Web Proxy Auto-Discovery Service' is check to see if the startup is set to 'disabled'.
Although PVWA hardening check (DisableServices) checks to see if the following services are disabled:
- Routing and Remote Access
- Smart Card
- Smart Card Removal Policy
- SNMP Trap
- Special Administration Console Helper
- Windows Error Reporting Service
**- WinHTTP Web Proxy Auto-Discovery Service**

With this:
- Is this a CyberArk recommendation
- Should this be added to the Public CyberArk Documentation?
- Should the PVWA hardening PowerShell automation scripts be updated to disable this service?
- When all of the services are set to 'disabled', the output in the html report indicates that this is 'good' although does not indicate the check being done, ie. checking that all of the following services are disabled:
     - "Routing and Remote Access", "Smart Card", "Smart Card Removal Policy", "SNMP Trap", "Special Administration Console Helper","Windows Error Reporting Service", "WinHTTP Web Proxy Auto-Discovery Service"

**Comment by AssafMiron** [comment]
Sorry @NathTheDude I'm not sure I'm clear on the issue here
Is the issue that we are checking that the WinHTTP Web Proxy Auto-Discovery Service although in v12 of PVWA hardening the script does not disable it
Or is the issue that we are not detailing that we verified that all services are disabled?
(or maybe both? :))

**Comment by NathTheDude** [comment]
> Sorry @NathTheDude I'm not sure I'm clear on the issue here
> Is the issue that we are checking that the WinHTTP Web Proxy Auto-Discovery Service although in v12 of PVWA hardening the script does not disable it
> Or is the issue that we are not detailing that we verified that all services are disabled?
> (or maybe both? :))

Hey @AssafMiron, I did not fully check what the output is if I enable of the services checked.

This was ran against a pvwa that was hardened by the CyberArk hardening scripts. The CyberArk hardening script does not disable the 'WinHTTP Web Proxy Auto-Discovery' service and it is not mentioned in the CyberArk documentation.

IMO, this should either be removed from has a check on the CYBR hardening check or added the the CyberArk hardening scripts so that this service is disabled.

**Comment by AssafMiron** [comment]
Hi @NathTheDude ,

Please see these following links:
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.4/en/Content/Security/EPV%20Out%20of%20Domain%20PVWA%20and%20CPM%20Server.htm#Additionalmanualsteps

https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.4/en/Content/Security/EPV%20GPO%20Settings%20-%20In%20Domain.htm

Where you can see that the 'WinHTTP Web Proxy Auto-Discovery' service is mentioned as a service that should be disabled
So I still think we should leave it in
If you find that this service is not disabled as part of the PVWA hardening script, maybe you should contact CyberArk support on this (I will try to ask someone internally as well)

Regards,
Assaf

**Comment by NathTheDude** [comment]
> Hi @NathTheDude ,
> 
> Please see these following links:
> https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.4/en/Content/Security/EPV%20Out%20of%20Domain%20PVWA%20and%20CPM%20Server.htm#Additionalmanualsteps
> 
> https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/11.4/en/Content/Security/EPV%20GPO%20Settings%20-%20In%20Domain.htm
> 
> Where you can see that the 'WinHTTP Web Proxy Auto-Discovery' service is mentioned as a service that should be disabled
> So I still think we should leave it in
> If you find that this service is not disabled as part of the PVWA hardening script, maybe you should contact CyberArk support on this (I will try to ask someone internally as well)
> 
> Regards,
> Assaf

Thanks @AssafMiron , right you are.

**Comment by AssafMiron** [comment]
Resolved 😄
