### ISSUE TITLE
PVWA Hardening - "PVWA Scheduled Task Service LocalUser"

### ISSUE THREAD

**Issue by NathTheDude** [cyberark/CYBRHardeningCheck#42]
The following step should be reviewed and udated:

'PVWA Scheduled Task Service LocalUser'

The CyberArk automation scripts no longer create this local user and therefore does not require any permissions on the logs folder, by default after hardening this service is still being managed by 'system' user.

**Comment by AssafMiron** [comment]
Duplicate (closing), see #6
