### ISSUE TITLE
Add a disclaimer to the prompt output and the report

### ISSUE THREAD

**Issue by itsmegb** [cyberark/CYBRHardeningCheck#53]
I think it would be beneficial if a disclaimer was added to the initial script output and the final report that these scripts are un-supported and that the output is for general hardening review only and not a compliance tool or a replacement for the official hardening guidelines.

This should help avoid issues being raised around the scripts with the CyberArk Support team and enforce the fact that these are only for review purposes only.

**Comment by AssafMiron** [comment]
That's a good idea
Can you think of a phrasing we can use?
Something like what we have in the readme maybe?

**Comment by itsmegb** [comment]
I think what is in the readme will work. It doesn't have to be much, but we need to make it clear that the tool is unsupported and is for informational purposes only.
Support cases are being raised around the findings from this tool, which isn't ideal.

**Comment by AssafMiron** [comment]
@itsmegb 
I added this as part of the new design - would you be able to have a look?
