### ISSUE TITLE
Win2019 Support Vault Hardening 

### ISSUE THREAD

**Issue by Nnr93** [cyberark/CYBRHardeningCheck#60]
## Is your feature request related to a problem? Please describe.

There is no Windows2019Audit.csv for Win 2019.

Could not complete Advanced Audit Policy Configuration validation.  Error: Source:mscorlib; Message: Could not find file 'C:\Users\Administrator\Desktop\Binary\CYBRHardeningCheck-main\CYBRHardeningCheck-main\CYBRHardeningCheck\Vault\Windows2019Audit.csv'.

## Describe the solution you would like

Include the Windows2019Audit.csv

## Describe alternatives you have considered

Copy and Rename  Windows2016Audit.csv to Windows2019Audit.csv

**Comment by AssafMiron** [comment]
Thanks for posting this issue @Nnr93 
At the moment Vault does not support Win2019 and that is why we still don't have Win2019 hardening check
once available, we will add it

**Comment by Nnr93** [comment]
@AssafMiron It is supported in 12.2. Please find the link below.

https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PAS%20SysReq/System%20Requirements%20-%20Digital%20Vault.htm?tocpath=Installation%7CSystem%20Requirements%7CSystem%20Requirements%20by%20Product%7C_____2#Minimumrequirements
![image](https://user-images.githubusercontent.com/31388714/130352943-7fce4234-3a6e-446e-8d74-61bb80b0ee13.png)

**Comment by AssafMiron** [comment]
You are correct, my miss
Thanks for noting, we will add this
