### ISSUE TITLE
Credential hardening check too broad

### ISSUE THREAD

**Issue by matiya** [cyberark/CYBRHardeningCheck#64]
The credentials hardening check looks for every file that matches *.ini, there are some files of the type:

`CredFileType=KeyPair`

like apigw.ini or apikey.ini that cannot be hardened (as far as I know) the same way as the other symmetric credential files.

**Comment by matiya** [comment]
To add a little more context, those files are not created with CreateCredFiles.exe but rather with ApieKeyManager.exe
https://docs.cyberark.com/Product-Doc/OnlineHelp/PAS/Latest/en/Content/PASIMP/APIKeyManager.htm

**Comment by NathTheDude** [comment]
@matiya , even though the cred files are different the check is against the value of the 'VerificationsFlag' which will not be a number that would cause the check to fail as far as I am aware.

Is the check failing on the different components for you? It passed on a quick check I did on my lab pvwa.

**Comment by matiya** [comment]
@NathTheDude I checked it in v11.4 and the test fails, but in a lab with v12.2 it was successful. 

However, I couldn't find any docs describing how to back up these credentials, in the link I posted above such an option doesn't seem to be available.

Could it be that in version > 12.1 the ApiKeyManager.exe performs this hardening without user interaction? (I can see that in the latest version there are .entropy files that were not there before).
If this is the case, then the hardening check will always fail in versions <12.1.

Translated with www.DeepL.com/Translator (free version)

**Comment by NathTheDude** [comment]
> @NathTheDude I checked it in v11.4 and the test fails, but in a lab with v12.2 it was successful. 
> 
> However, I couldn't find any docs describing how to back up these credentials, in the link I posted above such an option doesn't seem to be available.
> 
> Could it be that in version > 12.1 the ApiKeyManager.exe performs this hardening without user interaction? (I can see that in the latest version there are .entropy files that were not there before).
> If this is the case, then the hardening check will always fail in versions <12.1.
> 

@matiya , there was an update in 12.1 I think with the createcreatefile and I assume the apikeymnager utility. This can further secure the credential files further will many more options. That is the reason why the value against verificstionflags has gone up significantly.

**Comment by matiya** [comment]
@NathTheDude Alright then, but that would mean that this particular check works only in PAS v12.1 or higher?

**Comment by AssafMiron** [comment]
Hi @matiya ,
this check is been done automatically from v12.1 and up but it was also an option for earlier versions (manually)
So I think this is still a good indication that represent CyberArk best practices regarding CredFile hardening
Do you agree?

**Comment by matiya** [comment]
I do agree, the more checks and the more comprehensive they are, the better. I just wanted to make sure that I wasn't omitting a hardening step.
Now I wonder if a credential file generated with ApiKeyManager v12.1 would work in previous versions too.

Anyway I'll close the issue now, thank both of you for your time.
