### ISSUE TITLE
Incorrect check for Remote Desktop Services in PVWA and CPM 

### ISSUE THREAD

**Issue by matiya** [cyberark/CYBRHardeningCheck#65]
In GeneralHardeningSteps, there are two controls that are correct for PSM, but not for CPM/PVWA.

https://github.com/cyberark/CYBRHardeningCheck/blob/f68be075211a0844410b0fa204cb9f5decc00e91/CYBRHardeningCheck/bin/GeneralHardeningSteps.psm1#L419
https://github.com/cyberark/CYBRHardeningCheck/blob/f68be075211a0844410b0fa204cb9f5decc00e91/CYBRHardeningCheck/bin/GeneralHardeningSteps.psm1#L425

According to the latest GPO distributed by CyberArk in CPM/PVWA:

- Set rules for remote control of Remote Desktop Services user sessions = 0 (No remote control allowed)

- Set time limit for active but idle Remote Desktop Services sessions = 1

**Comment by AssafMiron** [comment]
Hi @matiya 
I uploaded a new branch with a fix to this issue - see #66 
would you mind checking if it solves the issue like you saw it?

Thanks,
Assaf

**Comment by matiya** [comment]
Hi @AssafMiron , I tested again in a lab with v12.2 and the branch linked but the script hangs:
![Animation258](https://user-images.githubusercontent.com/2721638/135244176-2d6fefa9-55ae-4f74-a121-652edb3ddaf1.gif)

Just to be sure I tested the main branch in the same machine and the script finishes ok.

**Comment by AssafMiron** [comment]
Thanks a lot for the feedback @matiya 
From the image you posted I see that the HTML report finished and also the PVWA checks - so the issue is not there (I assume)
I added a timeout for the hardening folder search (just in case) for maximum of 2 minutes so it would not hang

Did you try running it on a CPM/PVWA only machine or one that has PSM as well?

Did you look at the HTML report that was created before you ran the main version (or maybe you can look now, just to compare)

Thanks,
Assaf

**Comment by matiya** [comment]
@AssafMiron I ran again the script, and now it finishes but with the following error in the RDS Step.
```
[2021-09-30 09:05:57]	[INFO]	Start Step Remote Desktop Services
[2021-09-30 09:05:57]	[INFO]	Start RemoteDesktopServices
[2021-09-30 09:05:57]	[ERROR]	Could not validate Remote Server Services status.  Error: Source:System.Management.Automation; Message: The term 'init' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
[2021-09-30 09:05:57]	[INFO]	Finished Step Remote Desktop Services
```

The hardening status now outputs a more meaningful value:
pvwa-enhancements branch:
![image](https://user-images.githubusercontent.com/2721638/135404913-d6bf0782-7e02-4ec2-8422-663dca035040.png)
main branch:
![image](https://user-images.githubusercontent.com/2721638/135404942-4a873221-218c-4fc3-a634-86f9a6e08207.png)

**Comment by AssafMiron** [comment]
Thanks for testing @matiya 
It appears that I accidently deleted a comment sign next to the "init" word...
I update the commit and also updated the module number to represent the change
If you find it to be working now and also the hardening status makes more sense I can merge it to main

Thanks again for your help,
Assaf

**Comment by matiya** [comment]
Glad to be of help
Thank you for the fix.
