### ISSUE TITLE
Vault script - Add in a check to see if the 'server' keys have been CA Signed

### ISSUE THREAD

**Issue by NathTheDude-zz** [cyberark/CYBRHardeningCheck#7]
Are we able to check if the 'server' keys have been updated from being self-signed to being CA signed? With the keys being signed by the CA as I understand it the integrity of the keys are improved, by default SHA1 is used however if they are signed by the CA then this can be improved SHA 2-xxx.

If self signed keys are used then the following warning appears in the italog after each service restart:

ITATP151W Security warning - The Signature Hash Algorithm of the Vault certificate is SHA1. We recommend that you use at least Signature Hash Algorithm SHA2-256 with this Vault's configuration.

**Comment by itsmegb** [comment]
This warning would still appear if the cert was self-signed but using SHA1, so maybe both could be called out?
