### ISSUE TITLE
Vault script - issue with 'Vault_StaticIP' function - windows 2016 - vault v12

### ISSUE THREAD

**Issue by NathTheDude-zz** [cyberark/CYBRHardeningCheck#8]
When running the script on the vault an error is seen when running the function 'Vault_StaticIP'. The function uses the following:

`Get-NetIPAddress -InterfaceAlias "Ethernet" -AddressFamily IPv4`

With the vault in my lab the 'InterfaceAlias' name is 'Ethernet0', I suspect that this will vary between vaults for different customers.

Perhaps missing out the '-InterfaceAlias' will help to shorten the output, this output will obviously be different as well when customers have multiple network cards and are in a vault cluster?

Perhaps list all the network interfaces in the output that have an IPv4 address (minus the loopback interface) and state which adapters do not have statically assigned IP's?

**Comment by NathTheDude** [comment]
Currently I don't think this function is working, perhaps due to the error I mentioned. 

In my lab the vault has one NIC, if it has a static IP or a dynamic IP when the report is created the Hardening check 'Check that the Vault has Static IP' comes back as 'good'
