### ISSUE TITLE
Unable to complete the 'Advanced Audit Policy Configuration' step when running the script on the Vault server

### ISSUE THREAD

**Issue by Holland2209** [cyberark/CYBRHardeningCheck#88]
When running the hardening check script on the Vault (Primary and DR) server, the 'Advanced Audit Policy Configuration' step throws a warning with the following message.

Info: There was a problem verifying Advance Audit Policy Sub Category for 'Central Access Policy Staging'

The script output contained the following:

Checking Advance Audit Policy Sub Category for 'Central Access Policy Staging'
Error 0x00000057
The parameter is incorrect
There was a problem verifying Advance Audit Policy Sub Category for 'Central Access Policy Staging'

## Environment setup

- CyberArk v12.2.1: 
Vault (Primary and DR) server
PVWA and CPM server
PSM component server

**Note: seeing this issue with a customer who is running v12.1.

**Comment by AngryPanda25** [comment]
Good Day , I also have the same issues 

But I am not sure where and what to change in the files.
