### ISSUE TITLE
Vault script - Check no additional firewall rules exist in the windows firewall

### ISSUE THREAD

**Issue by NathTheDude-zz** [cyberark/CYBRHardeningCheck#9]
Would be good to check the firewall to see if there have been any manually added firewall rules added to the outgoing or incoming ranges.

Not sure how complicated the script needs to be for this check, I used the following before for a healthcheck to get the list or rules to a csv:

`function GetFirewallRules
{
$Direction = "*"
$RuleState = "*"
$Action = "*"
$hostname= hostname
$CSVFile = "$vComputerName-FirewallRules.csv"

$FirewallRules = Get-NetFirewallRule -DisplayName * -PolicyStore "ActiveStore"

$FirewallRuleSet = @()
ForEach ($Rule In $FirewallRules)
{
	Write-Output "Processing rule `"$($Rule.DisplayName)`" ($($Rule.Name))"

	$AdressFilter = $Rule | Get-NetFirewallAddressFilter
	$PortFilter = $Rule | Get-NetFirewallPortFilter
	$ApplicationFilter = $Rule | Get-NetFirewallApplicationFilter
	$ServiceFilter = $Rule | Get-NetFirewallServiceFilter
	$InterfaceFilter = $Rule | Get-NetFirewallInterfaceFilter
	$InterfaceTypeFilter = $Rule | Get-NetFirewallInterfaceTypeFilter
	$SecurityFilter = $Rule | Get-NetFirewallSecurityFilter

	$HashProps = [PSCustomObject]@{
		Name = $Rule.Name
		DisplayName = $Rule.DisplayName
		Description = $Rule.Description
		Group = $Rule.Group
		Enabled = $Rule.Enabled
		Profile = $Rule.Profile
		Platform = StringArrayToList $Rule.Platform
		Direction = $Rule.Direction
		Action = $Rule.Action
		EdgeTraversalPolicy = $Rule.EdgeTraversalPolicy
		LooseSourceMapping = $Rule.LooseSourceMapping
		LocalOnlyMapping = $Rule.LocalOnlyMapping
		Owner = $Rule.Owner
		LocalAddress = StringArrayToList $AdressFilter.LocalAddress
		RemoteAddress = StringArrayToList $AdressFilter.RemoteAddress
		Protocol = $PortFilter.Protocol
		LocalPort = StringArrayToList $PortFilter.LocalPort
		RemotePort = StringArrayToList $PortFilter.RemotePort
		IcmpType = StringArrayToList $PortFilter.IcmpType
		DynamicTarget = $PortFilter.DynamicTarget
		Program = $ApplicationFilter.Program -Replace "$($ENV:SystemRoot.Replace("\","\\"))\\", "%SystemRoot%\" -Replace "$(${ENV:ProgramFiles(x86)}.Replace("\","\\").Replace("(","\(").Replace(")","\)"))\\", "%ProgramFiles(x86)%\" -Replace "$($ENV:ProgramFiles.Replace("\","\\"))\\", "%ProgramFiles%\"
		Package = $ApplicationFilter.Package
		Service = $ServiceFilter.Service
		InterfaceAlias = StringArrayToList $InterfaceFilter.InterfaceAlias
		InterfaceType = $InterfaceTypeFilter.InterfaceType
		LocalUser = $SecurityFilter.LocalUser
		RemoteUser = $SecurityFilter.RemoteUser
		RemoteMachine = $SecurityFilter.RemoteMachine
		Authentication = $SecurityFilter.Authentication
		Encryption = $SecurityFilter.Encryption
		OverrideBlockRules = $SecurityFilter.OverrideBlockRules
	}

	$FirewallRuleSet += $HashProps
}

$FirewallRuleSet | ConvertTo-CSV -NoTypeInformation -Delimiter ";" | Set-Content "$Collect\System Information\$CSVFile"

}`

**Comment by itsmegb** [comment]
It might be possible to use parts of the HardenAzureFW.ps1 script from the Azure images, they iterate over the firewall rules for any that aren't in the CYBERARK_RULE.... group and then deletes them.
